export const ICONS = {
    BELL: '/icons/bell.png',
    CHAT: '/icons/chat.png',
    CROSS: '/icons/cross.svg',
    EDIT: '/icons/edit.svg',
    EMAIL_ICON: '/icons/email-icon.png',
    EYE_CLOSED: '/icons/eye-closed.svg',
    EYE_OPEN: '/icons/eye-open.svg',
    FACEBOOK: '/icons/facebook.png',
    FRUITS: '/icons/fruits.png',
    GOOGLE: '/icons/google.png',
    GOOGLE_SVG: '/icons/google.svg',
    HEART: '/icons/heart.svg',
    HOME: '/icons/home.svg',
    PHONE_CALL: '/icons/phone-call.png',
    PLUS: '/icons/plus.svg',
    QUESTION: '/icons/question.svg',
    QUOTE_REQUEST: '/icons/quote-request.png',
    SEARCH: '/icons/search.svg',
    SETTINGS: '/icons/settings.svg',
    SHOPPING_CART: '/icons/shopping-cart.svg',
    TRUCK_SIDE: '/icons/truck-side.svg',
    USERS: '/icons/users.svg',
    VEGETABLE: '/icons/vegetable.png',
    VERIFIED: '/icons/verified.png',
    VIDEO_CAMERA_ALT: '/icons/video-camera-alt.svg',
    GOODS: '/icons/goods.png',
    YES: '/icons/yes.png',
    THUNDER : '/icons/thunder.png',
}