export const LIVESTREAM_THUMBNAIL_WIDTH = 400;
export const LIVESTREAM_THUMBNAIL_HEIGHT = 192;
export const LIVESTREAM_AVATAR_SIZE = 48;
export const PLACEHOLDER_THUMBNAIL = '/img/products/placeholder.jpg';
export const PLACEHOLDER_AVATAR = '/icons/avatar.jpg';
export const SPINNER_SIZE = 16; // px
export const TIME_LOCALE = 'vi-VN';
export const TIME_OPTIONS = { hour: '2-digit', minute: '2-digit' } as const;
export const GRID_COLS = { base: 1, md: 2, xl: 3 } as const;
export const MAX_CONTENT_WIDTH = 7_000; // tailwind max-w value placeholder
