export const ORDER_CONFIG = {
  FALLBACK_IMAGE: '/img/Background.png',
  IMAGE_WIDTH: 80,
  IMAGE_HEIGHT: 80,
  IMAGE_SIZE_CLASS: 'w-20 h-20 sm:w-24 sm:h-24',
  DEFAULT_CURRENCY: 'VND',
  MAX_FRACTION_DIGITS: 0,
  DEFAULT_PAGE_LIMIT: 10,
  SUCCESS_MESSAGE_DURATION: 3000,
  CANCEL_REASON_MIN_LENGTH: 10,
  CANCEL_REASON_MAX_LENGTH: 500,
};
